dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install tox-travis
  - sudo apt-get -y install $(tox -qq -e bindep -- -b libvirt)
script:
  - tox -e lint
  - tox -e lint-docs
  - tox -e py -- tests/test_utils.py
