language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=lint-docs
      # NOTE(jhesketh): I could not find how to limit this to running only when
      #                 there are docs changes.

install:
  - pip install tox

script:
  - tox
