[aws]

# The node image by either ID or NAME (ami-image-id)
# Must be available in the region you have configured with aws-cli
ami_image_id = "ami-0a5b3ae0d9f2f7c9c"

# The node size or flavour name as known by the provider
node_size = "t2.xlarge"
