[libvirt]

connection = "qemu:///system"

# The range of networks to use across builds. Each instance of hardware will
# get a subnet inside this range given by libvirt_network_subnet. If multiple
# tests are being ran in parallel ensure there are enough subnets.
# (/20 with subnets of 26 will give 64 networks)
network_range = "192.168.128.0/20"

# Break network_range into subnets of the following size.
# (26 gives 64 hosts per hardware build/network)
network_subnet = 26

# The qcow2 image that will be used for libvirt. The image must
# contain cloud-init. This can be an system path or a URL which rookcheck will
# download.
image = "https://download.opensuse.org/distribution/leap/15.2/appliances/openSUSE-Leap-15.2-JeOS.x86_64-OpenStack-Cloud.qcow2"

# Memory use for libvirt VMs (in GB)
vm_memory = 8
