[ses]

# The target version of SES to install. This must match a key below that
# contains the repositories and yaml substitutions.

target = "cr_ses71"

  [ses.cr_ses71]
    rook_ceph_chart = "oci://registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/charts/ses/7.1/charts/rook-ceph"
    [ses.cr_ses71.yaml_substitutions]
      "registry.suse.com" = "registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers"

    [ses.cr_ses71.helm_values_substitutions]
      # We can't predict the pinned versions of containers, so instead of
      # supplying extra values.yaml files we perform substitutions
      "registry.suse.com" = "registry.suse.de/suse/sle-15-sp3/update/products/ses7/update/cr/containers"
      "#image: registry" = "image: registry"
      "#cephcsi:" = "cephcsi:"
      "#registrar:" = "registrar:"
      "#provisioner:" = "provisioner:"
      "#snapshotter:" = "snapshotter:"
      "#attacher:" = "attacher:"
      "#resizer:" = "resizer:"

    [ses.cr_ses71.repositories]
      # Each key/value under this sub-heading is a repository
      storage         = "http://download.suse.de/ibs/SUSE/Products/Storage/7.1/x86_64/product/"
      storage_updates = "http://download.suse.de/ibs/SUSE/Updates/Storage/7.1/x86_64/update/"

  [ses.devel71]
    rook_ceph_chart = "oci://registry.suse.de/devel/storage/7.0/pacific/charts/ses/7.1/charts/rook-ceph"

    [ses.devel71.yaml_substitutions]
      "registry.suse.com" = "registry.suse.de/devel/storage/7.0/pacific/containers"
      "# ROOK_CSI_" = "ROOK_CSI_"

    [ses.devel71.helm_values_substitutions]
      # We can't predict the pinned versions of containers, so instead of
      # supplying extra values.yaml files we perform substitutions
      "registry.suse.com" = "registry.suse.de/devel/storage/7.0/pacific/containers"
      "#image: registry" = "image: registry"
      "#cephcsi:" = "cephcsi:"
      "#registrar:" = "registrar:"
      "#provisioner:" = "provisioner:"
      "#snapshotter:" = "snapshotter:"
      "#attacher:" = "attacher:"
      "#resizer:" = "resizer:"
      "#  image: registry.k8s.io/sig-storage" = "  image: registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/cephcsi"
      "#  image: registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/cephcsi/cephcsi" = "  image: registry.suse.de/devel/storage/7.0/pacific/containers/ses/7.1/cephcsi/cephcsi"

    [ses.devel71.repositories]
      # Each key/value under this sub-heading is a repository
      storage        = "http://download.suse.de/ibs/SUSE/Products/Storage/7.1/x86_64/product/"
      storage_devel  = "https://download.suse.de/ibs/Devel:/Storage:/7.0:/Pacific/SLE_15_SP3/"
