[ses]

# Whether or not to build rook from git. If not, the target version of SES images
# are used.
build_rook_from_git = false

# Rook repo url
repo = "https://github.com/SUSE/rook"

# The rook version you want to test. This is the tag to be checked out so it must
# exist for real within rook repo
version = "master"

# The target version of SES to install. This must match a key below that
# contains the repositories and yaml substitutions.

target = "devel7"

  [ses.ses7]
    rook_ceph_chart = "registry.suse.de/suse/sle-15-sp2/update/products/ses7/charts/rook-ceph:latest"
    ceph_image = "registry.suse.de/devel/storage/7.0/containers/ses/7/rook/ceph:latest"
    [ses.ses7.yaml_substitutions]
      # "suse.com" = "suse.de/devel/storage/7.0/containers"

    [ses.ses7.repositories]
      # Each key/value under this sub-heading is a repository
      storage         = "http://download.suse.de/ibs/SUSE/Products/Storage/7/x86_64/product/"
      storage_updates = "http://download.suse.de/ibs/SUSE/Updates/Storage/7/x86_64/update/"

  [ses.devel7]
    rook_ceph_chart = "registry.suse.de/devel/storage/7.0/charts/ses/7/charts/rook-ceph:latest"
    ceph_image = "registry.suse.de/devel/storage/7.0/containers/ses/7/rook/ceph:latest"

    [ses.devel7.yaml_substitutions]
      "registry.suse.com" = "registry.suse.de/devel/storage/7.0/containers"
      "# ROOK_CSI_" = "ROOK_CSI_"

    [ses.devel7.repositories]
      # Each key/value under this sub-heading is a repository
      storage        = "http://download.suse.de/ibs/SUSE/Products/Storage/7/x86_64/product/"
      storage_devel  = "http://download.suse.de/ibs/Devel:/Storage:/7.0/SLE_15_SP2"
      storage_update = "http://download.suse.de/ibs/SUSE:/SLE-15-SP2:/Update:/Products:/SES7/standard/"
