[ses]

# The target version of SES to install. This must match a key below that
# contains the repositories and yaml substitutions.

target = "devel7"

  [ses.ses7]
    rook_ceph_chart = "oci://registry.suse.de/suse/sle-15-sp2/update/products/ses7/charts/rook-ceph"
    [ses.ses7.yaml_substitutions]
      # "registry.suse.com" = "registry.suse.de/devel/storage/7.0/containers"

    [ses.ses7.helm_values_substitutions]
      # We can't predict the pinned versions of containers, so instead of
      # supplying extra values.yaml files we perform substitutions

    [ses.ses7.repositories]
      # Each key/value under this sub-heading is a repository
      storage         = "http://download.suse.de/ibs/SUSE/Products/Storage/7/x86_64/product/"
      storage_updates = "http://download.suse.de/ibs/SUSE/Updates/Storage/7/x86_64/update/"

  [ses.devel7]
    rook_ceph_chart = "oci://registry.suse.de/devel/storage/7.0/charts/ses/7/charts/rook-ceph"

    [ses.devel7.yaml_substitutions]
      "registry.suse.com" = "registry.suse.de/devel/storage/7.0/containers"
      "# ROOK_CSI_" = "ROOK_CSI_"

    [ses.devel7.helm_values_substitutions]
      # We can't predict the pinned versions of containers, so instead of
      # supplying extra values.yaml files we perform substitutions
      "registry.suse.com" = "registry.suse.de/devel/storage/7.0/containers"
      "#image: registry" = "image: registry"
      "#cephcsi:" = "cephcsi:"
      "#registrar:" = "registrar:"
      "#provisioner:" = "provisioner:"
      "#snapshotter:" = "snapshotter:"
      "#attacher:" = "attacher:"
      "#resizer:" = "resizer:"

    [ses.devel7.repositories]
      # Each key/value under this sub-heading is a repository
      storage        = "http://download.suse.de/ibs/SUSE/Products/Storage/7/x86_64/product/"
      storage_devel  = "http://download.suse.de/ibs/Devel:/Storage:/7.0/SLE_15_SP2"
      storage_update = "http://download.suse.de/ibs/SUSE:/SLE-15-SP2:/Update:/Products:/SES7/standard/"
