# Prevent workspace/cluster collisions in shared environments with a resource
# name prefix.
# TODO(jhesketh): Add the datetime back into cluster_prefix
cluster_prefix = "@jinja rookcheck-{{env.USER}}-"

# The location for all of the build assets and state to be stored in. A
# sub-folder will be created using each CLUSTER_PREFIX
workspace_dir = "/tmp/rookcheck"

# A hardware provider (OPENSTACK, LIBVIRT, or AWS_EC2)
hardware_provider = "OPENSTACK"

# Set the number of master and worker nodes used by default for the cluster
number_masters = 1
number_workers = 3

# Set the initial number of data drives for workers
worker_initial_data_disks = 1

# The distro used on the underlying nodes
# Available options: openSUSE_k8s, SLES_CaaSP
distro = "openSUSE_k8s"

# The user to SSH into (must be root or sudoer). The node image is configured
# in the provider specific config file. Some providers may use a more specific
# user such as ec2_user.
node_image_user = "opensuse"

# Whether or not to perform some options as a thread. Turning this off may help
# with debugging at the cost of performance.
_use_threads = false

# Set _tear_down_cluster to False to keep the nodes and all the associated
# resources available after rookcheck has finished. Keep in mind that the
# created resources will need cleaning up manually afterwards.
# NOTE: This option forces _remove_workspace to be False.
_tear_down_cluster = true

# Set _tear_down_cluster_confirm to True to stop the tear down process
# and wait for user input (pressing enter).
# NOTE: This option is only useful if _tear_down_cluster is set to True
_tear_down_cluster_confirm = false

# If _gather_logs_dir is not empty, then after a run (successful or not) each
# abstraction (such as hardware, kubernetes, rook etc) will gather relevant
# logs and place them into this supplied relative or absolute path. This is
# useful for grabbing all of `kubectl describe` etc into build artifacts.
_gather_logs_dir = ""

# If set to True, the workspace and all created files from a test will be
# removed from the disk.
_remove_workspace = true

# Allow passing extra variables to Ansible. This can be in any format
# that ansible-playbook accepts for the --extra-vars parameter
# See https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-at-runtime  # noqa
ansible_extra_vars = ""
