name: Python Tox

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions bindep
        sudo apt-get update
        sudo apt-get -y install libvirt-clients libvirt-dev
    - name: Lint python
      run: tox -e lint
    - name: Lint docs
      run: tox -e lint-docs
    - name: utils unit tests
      run: tox -e py -- tests/test_utils.py
